create database if not exists delivery;

create table MAPS(
  ID_CITY INT(15) NOT NULL AUTO_INCREMENT,
  CITY VARCHAR(30) NOT NULL UNIQUE,
  LATILUDE DOUBLE NOT NULL,
  LONGTITUDE DOUBLE NOT NULL,
  PRIMARY KEY(ID_CITY)
);

create table WAGGONS(
  ID_WAGGON INT(15) NOT NULL AUTO_INCREMENT,
  NUMBER VARCHAR(7) NOT NULL UNIQUE,
  SHIFT_SIZE INT,
  ID_CITY INT NOT NULL,
  CAPACITY INT NOT NULL,
  STATUS ENUM('BROKEN', 'WORKING') NOT NULL,
  CURRENT_CITY VARCHAR(30) NOT NULL,
  PRIMARY KEY(ID_WAGGON),
  CONSTRAINT MAPS_ID_CITY_FK
  FOREIGN KEY(ID_CITY)
  REFERENCES MAPS (ID_CITY)
);

create table ORDERS(
  ID_ORDER INT(15) NOT NULL AUTO_INCREMENT,
  ORDER_STATUS ENUM('YES','NO') NOT NULL,
  ID_WAGGON INT NOT NULL,
  PRIMARY KEY(ID_ORDER),
  CONSTRAINT WAGGONS_ID_WAGGON_FK
  FOREIGN KEY(ID_WAGGON)
  REFERENCES WAGGONS(ID_WAGGON)
);

create table CARGO(
  ID_CARGO INT(15) NOT NULL AUTO_INCREMENT,
  REGISTRASION_NUMBER VARCHAR(7) NOT NULL,
  NAME VARCHAR(30) NOT NULL UNIQUE,
  WEIGHT INT NOT NULL,
  STATUS ENUM('PREPARED','SHIPPED','ADDED') NOT NULL,
  ID_ORDER INT NOT NULL,
  PRIMARY KEY(ID_CARGO),
  CONSTRAINT ORDERS_ID_ORDER_FK
  FOREIGN KEY(ID_ORDER)
  REFERENCES ORDERS (ID_ORDER)
);

create table WAY_POINTS(
  ID_WAY_POINT INT(15) NOT NULL AUTO_INCREMENT,
  ORDER_TYPE ENUM('LOADING','LANDING'),
  ID_CITY INT NOT NULL,
  ID_CARGO INT NOT NULL,
  ID_ORDER INT NOT NULL,
  PRIMARY KEY (ID_WAY_POINT),
  FOREIGN KEY (ID_ORDER) REFERENCES ORDERS(ID_ORDER),
  FOREIGN KEY (ID_CARGO) REFERENCES CARGO(ID_CARGO),
  FOREIGN KEY (ID_CITY) REFERENCES MAPS(ID_CITY)
);

create table DRIVERS(
  ID_DRIVER INT(15) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) NOT NULL,
  SECOND_NAME VARCHAR(30) NOT NULL,
  HOURS_WORKED INT NOT NULL,
  STATUS ENUM('REST','SHIFT','DRIVING'),
  ID_CITY INT NOT NULL,
  ID_WAGGON INT NOT NULL,
  PRIMARY KEY(ID_DRIVER),
  FOREIGN KEY (ID_CITY) REFERENCES MAPS(ID_CITY),
  FOREIGN KEY(ID_WAGGON)   REFERENCES WAGGONS(ID_WAGGON)
);
